Add docker compose.yml file generation
vlingo/xoom-designer pull request #146
Opened 2022-05-25 16:49 UTC by hamzajg

2022-05-26 05:03 UTC, VaughnVernon commented
@hamzajg Cool. Does this include images and configurations for all applicable options:

- RabbitMQ 
- Command Model Database
- Query Model Database 
- Others?

2022-05-26 07:28 UTC, hamzajg commented
> @hamzajg Cool. Does this include images and configurations for all applicable options:
> 
> * RabbitMQ
> * Command Model Database
> * Query Model Database
> * Others?

For now only RabbitMQ

2022-05-31 15:35 UTC, VaughnVernon requested changes
@hamzajg Cool! 👍🏻 Please see comments for database naming changes.

2022-05-31 15:35 UTC, VaughnVernon commented on src/test/resources/text-expectations/java/docker-compose-with-postgres-mysql.text
> +      MYSQL_DATABASE: xoomapp-query
@hamzajg Please name: xoomapp-query-model

2022-06-16 22:39 UTC, merged